# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc


alias gs="git status"
alias gss="git status -s" # short

alias ga="git add"
alias gaa="git add ." # add everything under that directory
alias gcm="git commit -m" # commit w/ message

alias gca="git commit --amend" # amend last commit

# take all uncommitted and un-staged changes currently in the working directory and add them
# to the previous commit, amending it before pushing the change up
# alias caa="commit -a --amend -C HEAD"

alias gac="git add . && git commit -m" # add everything & commit w/ message

# alias gpo="git push origin"
# alias gpullo="git pull origin" # pull from a repo you cloned
# alias gpullom="git pull origin master" # pull from master

alias gpuom="git pull origin master"
alias gpuod="git pull origin develop"

alias gpom="git push origin master"
alias gpod="git push origin develop"

alias gco="git checkout"
alias gcm="git checkout master"
alias gcd="git checkout develop"
alias gcob="git checkout -b" # create a new branch & checkout [+ branch-name]
alias gcomm="git checkout master && git merge" # merge into master [+ branch-name]

alias gl="git log"
alias goll='git log --pretty=format:"%C(yellow)%h\\ %ad%Cred%d\\ %Creset%s%Cblue\\ [%cn]" --decorate --date=short' # pretty one line log
alias gls="git log --stat" # view stats
alias glgraph="git log --graph --full-history --all --color" # from Andy

alias gb="git branch" # create branch [+ branch-name]
alias gbr="git branch -r" # view remote branches
alias gba="git branch -a" # view all branches
alias gbd="git branch -d" # delete branch that hasn't been merged into current branch [+ branch-name]

alias gmm="git merge -m" # merge w/ commit message [+ branch-name]
alias gmnc="git merge --no-commit" # merge w/o commit message [+ branch-name]

alias gvr="git remote -v" # view remotes

alias gtag="git tag" # list all tags

alias gpatto="git push --tags origin" # push all tags to origin

alias grm="git reset --merge" # undo last merge
alias grh="git reset --hard" # return to last committed state (you cannot undo a hard reset!)

# initialize a folder, add a readme file, commit w/ message
alias ginit='git init && echo "readme" >> README.md && git add . && git commit -m "Initial commit"'

# FullInit command
# Create folder, step into that folder, init, add readme, and commit with message
fullinit() {
  mkdir "$1" && cd "$1" && git init && echo "#$1" >> README.md && git add . && git commit -m "Initial commit"
}

# FOLDERS

# XAMPP htdocs - localhost
alias go-htdocs="cd c: && cd xampp/htdocs"


alias ls="ls -la"

alias ..="cd .."
alias ...="cd ../../"
alias ....="cd ../../../"

alias bp="vim ~/.bash_profile"
alias sbp="source ~/.bash_profile"

