# T&F - SassLint configuration

# Docs: https://github.com/sasstools/sass-lint
# Rules: https://github.com/sasstools/sass-lint/tree/master/docs/rules

# Disable rules:
#
# If you want SassLint to ignore a whole block,
# place your code block inside these comments, like so:
#
# // sass-lint:disable-all
# p {
#   margin: .5em;
# }
# // sass-lint:enable-all
#
# If you want to disable just one rule/line within a block,
# you can do the following (place to rule name to ignore
# after the command; find the rule name in this file ):
#
# p {
#   border: 0; // sass-lint:disable-line border-zero
# }
#
# Please also note that this YAML file can only accept spaces.

# Default severity  - warning or error
severity: warning

files:
  include:
    - 'dev/scss/**/*.scss'
  ignore:
    - 'dev/scss/_normalize.scss'

options:
  cache-config: true
  formatter: stylish
  merge-default-rules: false

rules:
  empty-line-between-blocks: 1
  extends-before-declarations: 1
  extends-before-mixins: 1
  indentation:
    - 1
    - size: tab
  leading-zero:
    - 1
    - include: true
  max-line-length: 80
  mixins-before-declarations: 1
  nesting-depth:
    - 1
    - max-depth: 4
  no-css-comments: 0
  no-duplicate-properties: 0
  no-empty-rulesets: 1
  no-extends: 1
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 1
  no-misspelled-properties:
    - 1
  no-vendor-prefixes: 2
  no-url-domains: 1
  no-trailing-whitespace: 1
  no-trailing-zero: 0
  one-declaration-per-line: 1
  placeholder-in-extend: 2
  quotes:
    - 1
    - style: double
  single-line-per-selector: 1
  space-after-colon:
    - 1
    - include: true
  space-after-comma:
    - 1
    - include: true
  space-before-bang:
    - 1
    - include: true
  space-before-brace:
    - 1
    - include: true
  space-before-colon:
    - 1
    - include: false
  space-between-parens:
    - 0
    - include: false
  trailing-semicolon: 2
  url-quotes: 1
  zero-unit:
    - 1
    - include: false
